#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd/system ]; then
            # Disable and stop radvd units
            for unit in $(systemctl list-units --all 'radvd-uplinkmgr@*' --no-legend | awk '{print $1;}'); do
                systemctl disable --now "$unit" || true
            done
        fi
        ;;
esac

#DEBHELPER#
