"""Config file generation for uplinkmgr-setup."""

from __future__ import annotations

import os
import sys
from pathlib import Path
from typing import Optional

from .config import Config, UplinkConfig, NetworkConfig
from . import naming


HEADER = "# Generated by uplinkmgr-setup. Do not edit by hand.\n# Regenerate with: uplinkmgr-setup\n"


# ---------------------------------------------------------------------------
# ifupdown
# ---------------------------------------------------------------------------

def interfaces_file(cfg: Config) -> str:
    lines = [HEADER]
    for uplink in cfg.uplinks:
        if not uplink.ipv6_pd:
            continue
        ll = naming.link_local(uplink.index)
        for net_idx, net in enumerate(cfg.networks):
            mv = naming.macvlan_name(net.interface, uplink.index)
            mac = naming.mac_address(uplink.index, net_idx)
            lines.append(f"auto {mv}")
            lines.append(f"iface {mv} inet manual")
            lines.append(f"    pre-up ip link add link {net.interface} name {mv} type macvlan mode bridge")
            lines.append(f"    pre-up ip link set {mv} address {mac}")
            lines.append(f"    pre-up sysctl -q net.ipv6.conf.{mv}.addr_gen_mode=1")
            lines.append(f"    up ip link set {mv} up")
            lines.append(f"    up ip -6 addr add {ll} dev {mv} scope link")
            lines.append(f"    down ip -6 addr del {ll} dev {mv} scope link 2>/dev/null || true")
            lines.append(f"    down ip link del {mv} 2>/dev/null || true")
            lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# dhcpcd config
# ---------------------------------------------------------------------------

def dhcpcd_conf(cfg: Config, head: str = "", tail: str = "") -> str:
    all_ifaces: list[str] = []
    for uplink in cfg.uplinks:
        all_ifaces.append(uplink.interface)
        if uplink.ipv6_pd:
            all_ifaces.extend(
                naming.macvlan_name(net.interface, uplink.index)
                for net in cfg.networks
            )

    lines = [f"allowinterfaces {' '.join(all_ifaces)}", ""]

    for uplink in cfg.uplinks:
        lines.append(f"interface {uplink.interface}")
        lines.append(f"    metric {uplink.metric}")
        if uplink.ipv6_pd or uplink.ia_na:
            lines.append("    ipv6rs")
            iaid = 1
            if uplink.ia_na:
                lines.append(f"    ia_na {iaid}")
                iaid += 1
            if uplink.ipv6_pd:
                pd_delegations = " ".join(
                    f"{naming.macvlan_name(net.interface, uplink.index)}/{net_idx}/64"
                    for net_idx, net in enumerate(cfg.networks)
                )
                lines.append(f"    ia_pd {iaid}/::/{uplink.ipv6_pd_hint} {pd_delegations}")
            lines.append("    duid")
        lines.append("")

    body = "\n".join(lines) + "\n"

    if head:
        if not head.endswith("\n"):
            head += "\n"
        body = head + "\n" + body
    if tail:
        if not tail.endswith("\n"):
            tail += "\n"
        body = body + "\n" + tail
    return HEADER + body


# ---------------------------------------------------------------------------
# radvd config (initial/placeholder — daemon regenerates with live lifetimes)
# ---------------------------------------------------------------------------

INITIAL_VALID_LIFETIME = 7200
INITIAL_PREFERRED_LIFETIME = 1800
INITIAL_DEFAULT_LIFETIME = 1800
INITIAL_ROUTE_LIFETIME = 1800


def radvd_conf(cfg: Config, uplink: UplinkConfig) -> str:
    """Generate initial radvd config. Uses placeholder lifetimes and ::/64 prefixes."""
    lines = [
        f"# Generated by uplinkmgr-setup for uplink: {uplink.name}",
        "# Do not edit by hand. The daemon regenerates this file with live lifetimes.",
        "",
    ]
    for net_idx, net in enumerate(cfg.networks):
        mv = naming.macvlan_name(net.interface, uplink.index)
        lines += _radvd_interface_block(
            iface=mv,
            preference="high",
            default_lifetime=INITIAL_DEFAULT_LIFETIME,
            route_lifetime=INITIAL_ROUTE_LIFETIME,
            prefix="::/64",
            valid_lifetime=INITIAL_VALID_LIFETIME,
            preferred_lifetime=INITIAL_PREFERRED_LIFETIME,
        )
    return "\n".join(lines) + "\n"


def radvd_conf_from_state(
    cfg: Config,
    uplink: UplinkConfig,
    preference: str,
    default_lifetime: int,
    route_lifetime: int,
    per_iface_prefixes: dict[str, str],  # macvlan_name -> prefix/64
    valid_lifetime: int,
    preferred_lifetime: int,
    is_down: bool = False,
) -> str:
    """Generate radvd config with live values from state files."""
    lines = [
        f"# Generated by uplinkmgr daemon for uplink: {uplink.name}",
        "# Do not edit by hand.",
        "",
    ]
    for net in cfg.networks:
        mv = naming.macvlan_name(net.interface, uplink.index)
        prefix = per_iface_prefixes.get(mv, "::/64")
        eff_preferred = 0 if is_down else preferred_lifetime
        eff_valid = 1800 if is_down else valid_lifetime
        lines += _radvd_interface_block(
            iface=mv,
            preference=preference,
            default_lifetime=default_lifetime,
            route_lifetime=route_lifetime,
            prefix=prefix,
            valid_lifetime=eff_valid,
            preferred_lifetime=eff_preferred,
        )
    return "\n".join(lines) + "\n"


def _radvd_interface_block(
    iface: str,
    preference: str,
    default_lifetime: int,
    route_lifetime: int,
    prefix: str,
    valid_lifetime: int,
    preferred_lifetime: int,
) -> list[str]:
    return [
        f"interface {iface}",
        "{",
        "    AdvSendAdvert on;",
        f"    AdvDefaultPreference {preference};",
        f"    AdvDefaultLifetime {default_lifetime};",
        "",
        "    route ::/0",
        "    {",
        f"        AdvRoutePreference {preference};",
        f"        AdvRouteLifetime {route_lifetime};",
        "    };",
        "",
        f"    prefix {prefix}",
        "    {",
        "        AdvOnLink on;",
        "        AdvAutonomous on;",
        "        AdvRouterAddr on;",
        f"        AdvValidLifetime {valid_lifetime};",
        f"        AdvPreferredLifetime {preferred_lifetime};",
        "        DecrementLifetimes on;",
        "    };",
        "",
        "    RDNSS { };",
        "    DNSSL { };",
        "};",
        "",
    ]


# ---------------------------------------------------------------------------
# radvd systemd unit
# ---------------------------------------------------------------------------

def radvd_template_unit() -> str:
    return (
        "# Generated by uplinkmgr-setup.\n"
        "# Do not edit by hand.\n"
        "\n"
        "[Unit]\n"
        "Description=Router advertisement daemon for uplinkmgr uplink: %i\n"
        "After=network.target dhcpcd.service\n"
        "Requires=dhcpcd.service\n"
        "\n"
        "[Service]\n"
        "Type=forking\n"
        "PIDFile=/run/radvd-uplinkmgr-%i.pid\n"
        "ExecStart=/usr/sbin/radvd --configtest --config /etc/uplinkmgr/radvd/radvd-uplinkmgr-%i.conf\n"
        "ExecStart=/usr/sbin/radvd \\\n"
        "    --config /etc/uplinkmgr/radvd/radvd-uplinkmgr-%i.conf \\\n"
        "    --pidfile /run/radvd-uplinkmgr-%i.pid \\\n"
        "    --nodaemon\n"
        "ExecReload=/bin/kill -HUP $MAINPID\n"
        "Restart=on-failure\n"
        "RestartSec=5s\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
    )


# ---------------------------------------------------------------------------
# Routing table registration
# ---------------------------------------------------------------------------

def rt_tables(cfg: Config) -> str:
    lines = [HEADER, ""]
    lines.append(f"{naming.ipv4_table_num(cfg.routing_table_start)}\t{naming.ipv4_table_name()}")
    for uplink in cfg.uplinks:
        num = naming.ipv6_table_num(cfg.routing_table_start, uplink.index)
        name = naming.ipv6_table_name(uplink.name)
        lines.append(f"{num}\t{name}")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Uplink environment files
# ---------------------------------------------------------------------------

def env_file(cfg: Config, uplink: UplinkConfig) -> str:
    return (
        f"# Generated by uplinkmgr-setup for uplink: {uplink.name}\n"
        f"# Do not edit by hand.\n"
        f"UPLINKMGR_UPLINK_NAME={uplink.name}\n"
        f"UPLINKMGR_WAN_IFACE={uplink.interface}\n"
        f"UPLINKMGR_IPV6_PD={'true' if uplink.ipv6_pd else 'false'}\n"
        f"UPLINKMGR_IPV6_IA_NA={'true' if uplink.ia_na else 'false'}\n"
    )


# ---------------------------------------------------------------------------
# NAT reference fragment
# ---------------------------------------------------------------------------

def nat_fragment(cfg: Config) -> str:
    wan_rules = "\n".join(
        f'        oifname "{u.interface}" masquerade'
        for u in cfg.uplinks
    )
    return (
        "# NAT reference fragment generated by uplinkmgr-setup.\n"
        "# This file is NOT applied automatically.\n"
        "# Review and incorporate into your nftables configuration as appropriate.\n"
        "# Regenerate with: uplinkmgr-setup\n"
        "\n"
        "table ip uplinkmgr_nat {\n"
        "    chain postrouting {\n"
        "        type nat hook postrouting priority srcnat; policy accept;\n"
        "\n"
        "        # Masquerade outbound traffic on all WAN interfaces\n"
        f"{wan_rules}\n"
        "    }\n"
        "}\n"
    )


# ---------------------------------------------------------------------------
# Write helpers
# ---------------------------------------------------------------------------

def write_file(path: str, content: str, dry_run: bool = False) -> None:
    if dry_run:
        print(f"--- {path} ---")
        print(content)
        return
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)


def write_symlink(link_path: str, target_name: str, dry_run: bool = False) -> None:
    """Create a symlink link_path -> target_name (basename only)."""
    if dry_run:
        print(f"symlink: {link_path} -> {target_name}")
        return
    p = Path(link_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if p.is_symlink() or p.exists():
        p.unlink()
    p.symlink_to(target_name)


def remove_stale_files(pattern_dir: str, prefix: str, current_names: set[str],
                        suffix: str, dry_run: bool = False) -> None:
    """Remove generated files whose uplink name is no longer in current_names."""
    d = Path(pattern_dir)
    if not d.exists():
        return
    for f in d.iterdir():
        if f.name.startswith(prefix) and f.name.endswith(suffix):
            inner = f.name[len(prefix):-len(suffix)]
            if inner not in current_names:
                if dry_run:
                    print(f"would remove: {f}")
                else:
                    f.unlink()
